Numpy: Package for multidimesional array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(1,31,5) #shift+tab -> help box

array([ 1,  6, 11, 16, 21, 26])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3,5)

array([[0.19344408, 0.80513367, 0.38133922, 0.31123743, 0.01319497],
       [0.39064639, 0.09971474, 0.13683267, 0.48868564, 0.66370855],
       [0.15195735, 0.59265316, 0.87067747, 0.83937468, 0.03586878]])

In [24]:
arr=np.random.randn(2,4)
arr

array([[ 1.13508384, -1.41948354, -0.9881764 ,  2.77385826],
       [ 1.3660203 ,  2.36796596,  0.83059363, -0.31531575]])

In [25]:
np.random.randint(2,100)

16

In [26]:
np.random.randint(20,56,100)

array([33, 55, 24, 46, 43, 39, 48, 31, 37, 30, 32, 40, 21, 32, 33, 51, 36,
       26, 48, 24, 43, 44, 51, 42, 54, 31, 32, 31, 34, 54, 54, 38, 38, 50,
       24, 48, 27, 36, 20, 32, 21, 48, 44, 32, 38, 21, 51, 30, 50, 24, 20,
       32, 55, 21, 21, 40, 34, 40, 36, 34, 49, 20, 46, 36, 51, 33, 54, 55,
       23, 50, 48, 35, 45, 50, 29, 32, 46, 41, 50, 46, 30, 47, 44, 40, 27,
       22, 55, 48, 26, 26, 25, 32, 35, 47, 48, 47, 29, 35, 30, 32])

In [29]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
rand_array=np.random.randint(0,100,20)
rand_array

array([23, 61, 13, 82, 44, 97, 31, 34,  7, 36, 26, 98, 25, 85, 61, 55, 63,
       42, 80,  4])

In [31]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [33]:
rand_array.max()

98

In [40]:
rand_array.argmax()

11

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)
a

array([[0.41302571, 0.83963232, 0.9662364 ],
       [0.80134512, 0.92227079, 0.34666282]])

In [37]:
a.T

array([[0.41302571, 0.80134512],
       [0.83963232, 0.92227079],
       [0.9662364 , 0.34666282]])

In [41]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
sample_array[2:5]

array([12, 13, 14])

In [43]:
sample_array[0]

10

In [44]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [45]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [48]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [49]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two dimensional array 

In [50]:
import numpy as np

In [51]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [52]:
sample_matrix[1,2]

21

In [53]:
sample_matrix[2,1]

76

In [54]:
sample_matrix[2]

array([56, 76, 24,  7])

In [55]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# Selection Techniques

In [57]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [60]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [61]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [62]:
np.max(sample_array)

19

In [63]:
np.min(sample_array)

1

In [64]:
np.argmax(sample_array)

18

In [65]:
np.argmin(sample_array)

0

In [66]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [67]:
np.std(sample_array)

5.477225575051661

In [68]:
np.var(sample_array)

30.0

In [69]:
np.mean(sample_array)

10.0

In [70]:
array=np.random.randn(3,4)
array

array([[ 0.65780632, -1.50517331, -0.21715057,  3.05013026],
       [-0.68319467,  0.69432597, -0.2278035 , -1.23615093],
       [ 0.56513295, -0.41692639,  1.22111856,  1.2861039 ]])

In [71]:
np.round(array,decimals=2)

array([[ 0.66, -1.51, -0.22,  3.05],
       [-0.68,  0.69, -0.23, -1.24],
       [ 0.57, -0.42,  1.22,  1.29]])

In [72]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')